- name: Restart sssd
  service: name=sssd state=restarted enabled=yes
  listen: "restart sssd"

- name: Reload systemd
  systemd:
    daemon_reload: true
  listen: "reload systemd"

- name: Restart rpc-gssd
  systemd:
    name: rpc-gssd
    daemon_reload: true
    state: restarted
  notify: "restart rpc-gssd"

- name: Reload sshd
  systemd:
    name: sshd
    state: reloaded
  notify: "reload sshd"
