basedn: "{{ 'dc=' + ( ansible_domain | replace('^.','') | replace('.$','') | replace('.',',dc=')) }}"
ldap_server: ldap
krb_server: kerberos
sssd_min_id: 5000
sssd_min_id: 20000
sssd_admin_only: false
