- name: Restart slapd
  ansible.builtin.systemd: name=slapd state=restarted enabled=yes
  listen: "restart slapd"

- name: Restart krb5-kdc
  ansible.builtin.systemd: name=krb5-kdc state=restarted enabled=yes
  listen: "restart krb5-kdc"

- name: Restart krb5-admin-server
  ansible.builtin.systemd: name=krb5-admin-server state=restarted enabled=yes
  listen: "restart krb5-admin-server"

- name: Reload UFW
  community.general.ufw:
    state: reloaded
  listen: "reload ufw"
