# Update lists and upgrade packages

- name: Update apt package lists
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 86400

- name: Upgrade packages
  ansible.builtin.apt:
    upgrade: dist
    autoremove: true
    autoclean: true

- name: Install extra packages
  ansible.builtin.apt:
    name: "{{ extra_pkgs }}"
    state: latest # noqa package-latest
  when: extra_pkgs | length > 0

- name: Add backports repository
  ansible.builtin.apt_repository:
    repo: deb http://deb.debian.org/debian/ {{ ansible_distribution_release }}-backports main non-free-firmware
    state: present
    update_cache: true
  when: extra_pkgs_bpo | length > 0

- name: Install extra packages from backports
  ansible.builtin.apt:
    name: "{{ extra_pkgs_bpo }}"
    state: latest # noqa package-latest
    default_release: "{{ ansible_distribution_release }}-backports"
  when: extra_pkgs_bpo | length > 0
